version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  AfterInstall:
    - location: bash pipeline/setup_dependencies.sh
      timeout: 60
  # ApplicationStart:
  #   - location: pipeline/handle_run_app.sh