version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/AQI/
hooks:
  # BeforeInstall:
  #   - location: scripts/testGPIO.sh
  #     timeout: 60
  #     runas: root
  # AfterInstall:
  #   - location: scripts/testSensors.sh
  #     timeout: 300
  #     runas: root
  ApplicationStart:
    - location: flask run
      timeout: 300
      runas: root